FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps
COPY . .
ENV REACT_APP_FRAPPE_URL=https://office.enfonoerp.com
RUN npm run build

FROM caddy:2-alpine
COPY --from=build /app/build /srv/enfono
